name: Publish Mathive Thoughts
run-name: Publishing ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Cache gitlibs
        uses: actions/cache@v4
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}
          restore-keys: gitlibs-

      - name: Build
        run: make build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/powerpack/

  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
